### ISSUE TITLE
Polar coordinates?

### ISSUE THREAD

**Issue by mccartney** [susam/fxyt#3]
I think it would work great if it came with support for polar coordinates, thus making the pictures more "circular".

**Comment by susam** [comment]
So instead of evaluating f(x, y, t), we evaluate f(r, θ, t)? That does sound like a very interesting idea. Thanks for sharing! It sounds like it deserves its own project, say, a project named FRΘT. If anyone is interested to implement it, please feel free to reuse the code in this project under the terms of the MIT license.

By the way, I know at least one FXYT demo that makes circular animation with FXYT. Quoting [TJSomething](https://news.ycombinator.com/user?id=TJSomething):

> I got this fun little ripple effect by implementing Newton's method to do a square root.
>
> https://susam.net/fxyt.html#MXN127dDpYN127dDpsN5qDN2qNN6bRRSDRDRSqsN2qRcPSPTN2pdN20rN12p

**Comment by mccartney** [comment]
Working version
![image](https://github.com/susam/fxyt/assets/762437/0a7ba36d-e52a-49a5-928d-0b47f22a657c)

**Comment by mccartney** [comment]
Actually all the basics like checkers pattern look interesting here:
![image](https://github.com/susam/fxyt/assets/762437/5e870656-a4bd-49f5-a06c-ee2987d0a7d2)

**Comment by susam** [comment]
Closing this open issue now.  I am glad you came across this project and developed a version of it with polar coordinates.

**Comment by adlai** [comment]
> Working version

is your code uploaded anywhere?

GitHub reports that your fork is neither ahead nor up-to-date of this one, suggesting you either kept the code private, or changed the project's name...

**Comment by mccartney** [comment]
@adlai, indeed I must've lost the code somewhere, probably some git operation blooper on my side.

Anyway, I've just recreated it in https://github.com/mccartney/fxyt/commit/cb24061b726b7c246fdbb212c6062af640ce03f2
